### ISSUE TITLE
'GlobalStorage' object has no attribute 'face'

### ISSUE THREAD

**Issue by crazysal** [rusty1s/deep-graph-matching-consensus#15]
Context  :

```
(pop) sahmed9@alice:~/reps/deep-graph-matching-consensus/examples$ CUDA_VISIBLE_DEVICES=3 python pascal.py 

Processing...

Done!
Traceback (most recent call last):
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 48, in __getattr__
    return self[key]
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 68, in __getitem__
    return self._mapping[key]
KeyError: 'face'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pascal.py", line 37, in <module>
    train_datasets += [ValidPairDataset(dataset, dataset, sample=True)]
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/dgmc-1.0.0-py3.8.egg/dgmc/utils/data.py", line 80, in __init__
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/dgmc-1.0.0-py3.8.egg/dgmc/utils/data.py", line 84, in __compute_pairs__
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 199, in __getitem__
    data = data if self.transform is None else self.transform(data)
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/transforms/compose.py", line 20, in __call__
    data = transform(data)
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/transforms/face_to_edge.py", line 19, in __call__
    if data.face is not None:
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/data/data.py", line 345, in __getattr__
    return getattr(self._store, key)
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 50, in __getattr__
    raise AttributeError(
AttributeError: 'GlobalStorage' object has no attribute 'face'

```

env : 
```
# packages in environment at /home/sahmed9/anaconda3/envs/pop:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
blas                      1.0                         mkl  
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
cffi                      1.14.6           py38ha65f79e_0    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              3.4.7            py38ha5dfef3_0    conda-forge
cudatoolkit               11.1.74              h6bb024c_0    nvidia
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
ffmpeg                    4.2.2                h20bf706_0  
freetype                  2.10.4               h5ab3b9f_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
intel-openmp              2021.3.0          h06a4308_3350  
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9b                   h024ee3a_2  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               h14aa051_19    conda-forge
libgfortran4              7.5.0               h14aa051_19    conda-forge
libgomp                   9.3.0               h5101ec6_17  
libidn2                   2.3.2                h7f8727e_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libuv                     1.40.0               h7b6447c_0  
libvpx                    1.7.0                h439df22_0  
libwebp-base              1.2.0                h27cfd23_0  
lz4-c                     1.9.3                h295c915_1  
markupsafe                2.0.1            py38h497a2fe_0    conda-forge
mkl                       2021.3.0           h06a4308_520  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.0            py38h42c9631_2  
mkl_random                1.2.2            py38h51133e4_0  
ncurses                   6.2                  he6710b0_1  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.5                        py_0    conda-forge
ninja                     1.10.2               hff7bd54_1  
numpy                     1.20.3           py38hf144106_0  
numpy-base                1.20.3           py38h74d4b33_0  
olefile                   0.46               pyhd3eb1b0_0  
openh264                  2.1.0                hd408876_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   1.1.1k               h7f98852_0    conda-forge
pandas                    1.3.1            py38h1abd341_0    conda-forge
pillow                    8.3.1            py38h2c7a002_0  
pip                       21.2.2           py38h06a4308_0  
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyg                       2.0.1           py38_torch_1.8.0_cu111    pyg
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
python                    3.8.11          h12debd9_0_cpython  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-louvain            0.15               pyhd3deb0d_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.8.2           py3.8_cuda11.1_cudnn8.0.5_0    pytorch-lts
pytorch-cluster           1.5.9           py38_torch_1.8.0_cu111    pyg
pytorch-scatter           2.0.8           py38_torch_1.8.0_cu111    pyg
pytorch-sparse            0.6.12          py38_torch_1.8.0_cu111    pyg
pytorch-spline-conv       1.2.1           py38_torch_1.8.0_cu111    pyg
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
readline                  8.1                  h27cfd23_0  
requests                  2.25.1             pyhd3deb0d_0    conda-forge
scikit-learn              0.24.2           py38ha9443f7_0  
scipy                     1.7.1            py38h292c36d_2  
setuptools                58.0.4           py38h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.36.0               hc218d9a_0  
threadpoolctl             2.2.0              pyh8a188c0_0    conda-forge
tk                        8.6.10               hbc83047_0  
torchaudio                0.8.2                      py38    pytorch-lts
torchvision               0.9.2                py38_cu111    pytorch-lts
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
typing_extensions         3.10.0.2           pyh06a4308_0  
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd3eb1b0_1  
x264                      1!157.20191217       h7b6447c_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0  

```

**Comment by rusty1s** [comment]
Thanks for reporting. This issue is introduced in PyG 2.0, and it is now fixed in PyG master, see [here](https://github.com/pyg-team/pytorch_geometric/commit/724ec4cb088d68e3fbba7c4152073b6a30c9f6ab). You can either apply the change locally, or install PyG from master to fix this.
