### ISSUE TITLE
About the downloading datesets

### ISSUE THREAD

**Issue by jackzhangfx** [rusty1s/deep-graph-matching-consensus#9]

**Comment by jackzhangfx** [comment]
when i run "python dbp15k --category=zh_en", i catched this error:

Downloading 1dYJtj1_J4nYJdrDY95ucGLCuZXDXI7PL into ..\data\DBP15K\raw.zip... Traceback (most recent call last):
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\urllib3\connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\urllib3\connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001F996DAF390>: Failed to establish a new connection: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1dYJtj1_J4nYJdrDY95ucGLCuZXDXI7PL (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object
at 0x000001F996DAF390>: Failed to establish a new connection: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dbp15k.py", line 27, in <module>
    data = DBP15K(path, args.category, transform=SumEmbedding())[0].to(device)
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\torch_geometric\datasets\dbp15k.py", line 40, in __init__
    super(DBP15K, self).__init__(root, transform, pre_transform)
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 54, in __init__
    pre_filter)
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\torch_geometric\data\dataset.py", line 89, in __init__
    self._download()
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\torch_geometric\data\dataset.py", line 141, in _download
    self.download()
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\torch_geometric\datasets\dbp15k.py", line 53, in download
    gdd.download_file_from_google_drive(self.file_id, path)
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\google_drive_downloader\google_drive_downloader.py", line 56, in download_file_from_google_drive
    response = session.get(GoogleDriveDownloader.DOWNLOAD_URL, params={'id': file_id}, stream=True)
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda3\envs\torchgpu\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1dYJtj1_J4nYJdrDY95ucGLCuZXDXI7PL (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection obje
ct at 0x000001F996DAF390>: Failed to establish a new connection: [WinError 10060]

**Comment by jackzhangfx** [comment]
solved

**Comment by rusty1s** [comment]
Awesome :) You can alternatively download them directly from [here](https://drive.google.com/open?id=1dYJtj1_J4nYJdrDY95ucGLCuZXDXI7PL).
